version: '3.9'

services:

  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - ./tileserver-gl:/data

  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - ZOOM_LEVEL=${ZOOM_LEVEL}
    volumes:
      - ./backend/src:/app/src
      - ./backend/api.js:/app/api.js
      - ./backend/data/austria.geojson:/data/austria.geojson
      - ./logs/:/logs/
    ports:
      - "3000:3000"
    command: ["npm", "run", "${OPMODE}"]
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend/src:/app/src
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local