version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./data:/data
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - ZOOM_LEVEL=16

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  tilesdata: