version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    environment:
      - ZOOM_LEVEL=16
      - SLEEP_BETWEEN_REQUESTS=100
    volumes:
      - ./data:/data

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  tilesdata: